### ISSUE TITLE
Cannot Generate

### ISSUE THREAD

**Issue by mbitson** [corestoreio/csfw#5]
Hey There!

I'm attempting to setup your framework, see what it's capable of, and then looking into building an AngularJS administration panel/frontend for this framework. I'm a frontend (js, css, html) & PHP developer with a tiny bit of golang experience, so I fear I may be useless on the golang side for awhile. That being said, I'd love to use a project like this for many of my clients and would like to contribute in any way I can.

However, I can't even get it to generate yet. :D My error says:
```
root@go:/home/go/src/github.com/corestoreio/csfw# go generate ./...
can't load package: package github.com/corestoreio/csfw/tools/csMake: cannot find package "github.com/corestoreio/csfw/tools/csMake" in any of:
        /root/.gvm/gos/go1.4.2/src/github.com/corestoreio/csfw/tools/csMake (from $GOROOT)
        /home/go/src/github.com/corestoreio/csfw/tools/csMake (from $GOPATH)
csfw.go:1: running "go": exit status 1
```

It appears to be unable to find github.com/corestoreio/csfw/tools/csMake- which I can't find either. Has this been removed? Am I missing something?

Thanks!

**Comment by SchumacherFM** [comment]
Hey Mikel,

sorry to disappoint you but there is a huge refactoring going on because architecture does not fit.

The framework is currently capable of nothing (despite some packages are already working). If you have in-depth Magento knowledge from a backend side then you can help me :-)

Cheers, Cyrill

**Comment by mbitson** [comment]
Hey Schumacher- I am a Magento certified developer and I'm quite familiar with the Magento Architecture. I may be able to assist with creating the golang interfaces, let me look into this, read the code you have so far, and see how I could help. (unless you've got a particular item you'd like me to try and tackle?) My previous golang projects have been built within golang frameworks, such as Beego. Will you be (eventually) making a UI to manage/view the store through this framework? Do you plan on making it it's own ecommerce system just with backwards support for Magento databases?

Thanks!

**Comment by SchumacherFM** [comment]
At the moment UI is a far far future. First I need the core API, like eav, store and config package.

A starting point would be for you:
-  the eav package. Can be very very complex.
- i18n and locale packages to include the latest changes from golang.org/x/text
- package email to implement a daemon manager which takes care for each daemon of a store view
