### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gedw99** [corestoreio/csfw#8]
does this rely on magento ?

I ask because i dont want to use this with magento, but rather with my own acconting software for myself.

**Comment by SchumacherFM** [comment]
For now those packages don't work and are getting refactored. They don't even compile.

In general it relys on the Magento database schema which is in my opinion 90% perfect. There are some flaws in it which I might want to eliminate but this change makes this project incompatible to a running and existing Magento installation.

You can read here more: https://cyrillschumacher.com/2016/12/12/avoiding-duplicate-content-in-magentos-eav-model/

**Comment by joeblew99** [comment]
Ok thanks. I see what you mean from the article.
