### ISSUE TITLE
How usage?

### ISSUE THREAD

**Issue by xinuxZ** [corestoreio/csfw#9]
I do as you said in README , but it does't work.

1. codegen  dir not exists 
2. I copy _codegen  as codegen  , then run "go run codegen/tableToStruct/*.go" in  command line, encounter error:
codegen/tableToStruct/helper.go:24:2: cannot find package "github.com/corestoreio/csfw/util/magento"

**Comment by SchumacherFM** [comment]
Hi,

sorry these packages are still in development mode. Everywhere are breaking changes and code.

**Comment by xinuxZ** [comment]
OK thinks
